sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t shengcer/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true shengcer/react-test npm test -- --coverage
after_success:
  - docker build -t shengcer/multi-client ./client
  - docker build -t shengcer/multi-nginx ./nginx
  - docker build -t shengcer/multi-server ./server
  - docker build -t shengcer/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shengcer/multi-client 
  - docker push shengcer/multi-nginx
  - docker push shengcer/multi-server
  - docker push shengcer/multi-worker
